version: '3'
services:
  phphttp:
    build:
      context: ./build/docker/phphttp
      dockerfile: Dockerfile
    image: phphttp
    ports:
      - '8085:80'
    volumes:
      - '.:/var/www/html'
      - './build/config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'