services:
  _defaults:
    autowire: true
    autoconfigure: false

  Src\:
    resource: '../src/*'

  Src\PlayerMatcher\Adapters\Api\Controllers\GameEndpoint:
    public: true

  Src\PlayerMatcher\Adapters\Api\Controllers\PlayerEndpoint:
    public: true